
export const GENERATE_TEST_QUESTIONNAIRE_SUCCESS = 'royalsatwork/Home/GENERATE_TEST_QUESTIONNAIRE_SUCCESS';
export const GENERATE_TEST_QUESTIONNAIRE_ERROR = 'royalsatwork/Home/GENERATE_TEST_QUESTIONNAIRE_ERROR';
